01.04.24

diff --git a/scripts/term-scripts/term-get-fg b/scripts/term-scripts/term-get-fg
--- a/scripts/term-scripts/term-get-fg
+++ b/scripts/term-scripts/term-get-fg
@@ -3,5 +3,26 @@ export TTY
 
 # ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null
 
-IFS=";" read -a REPLY -s -t 0.25 -d "S" -p $'\e[?1;1;0S' >&2
-[[ ${REPLY[1]} == "0" ]] && echo "${REPLY[2]}"
+timeout=0.25
+
+IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]11;?\e\\' >&2
+
+if [[ ${REPLY[1]} =~ ^rgb ]]; then
+	# Return value format: $'\e]11;rgb:ffff/0000/ffff\e\\'.
+	# ImageMagick wants colors formatted as #ffff0000ffff.
+	background='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+	IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]10;?\e\\' >&2
+	if [[ ${REPLY[1]} =~ ^rgb ]]; then
+	    foreground='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+	    # Check for "Reverse Video" (DECSCNM screen mode).
+	    IFS=";?$"  read -a REPLY -s -t ${timeout} -d "y" -p $'\e[?5$p'
+	    if [[ ${REPLY[2]} == 1 || ${REPLY[2]} == 3 ]]; then
+		temp=$foreground
+		foreground=$background
+		background=$temp
+	    fi
+
+	    echo "foreground=$foreground"
+	    echo "background=$background"
+	fi
+fi
