1649206403

diff --git a/scripts/guru b/scripts/guru
--- a/scripts/guru
+++ b/scripts/guru
@@ -1,7 +1,120 @@
 #!/bin/bash
 export TTY
 
-# Guru takes the terminal contents and chats about it
-# pj:guru
+sn="$(basename "$0")"
 
-nlsh
+# Apostrophe
+# Version 1.0, bash
+
+# Apostrophe is a figure of speech in which a speaker directly addresses someone
+# (or something) that is not present or cannot respond in reality. ... An
+# apostrophe is often introduced by the exclamation "O," as when Juliet cries
+# out: "O Romeo, Romeo, Wherefore art thou Romeo?"
+
+FRAMETYPE=tty
+
+apostrophe-logo 1>&2
+
+while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
+    "") { shift; }; ;;
+    -nv) {
+        USE_NVC=y
+        shift
+    }
+    ;;
+
+    -human|-talk-to-human) {
+        PEN_ENGINE=Human
+        shift
+    }
+    ;;
+
+    -engine) {
+        PEN_ENGINE="$2"
+        shift
+        shift
+    }
+    ;;
+
+    -temp|-temperature) {
+        export PEN_TEMPERATURE="$2"
+        shift
+        shift
+    }
+    ;;
+
+    -tty|-nw|-t) {
+        export PEN_USE_GUI=n
+        FRAMETYPE=tty
+        shift
+    }
+    ;;
+
+    -context) {
+        context="$2"
+        shift
+        shift
+    }
+    ;;
+
+    -win) {
+        context="$(pen-tm cap-pane -nohist)"
+        shift
+    }
+    ;;
+
+    -gui) {
+        export PEN_USE_GUI=y
+        FRAMETYPE=gui
+        shift
+    }
+    ;;
+
+    *) break;
+esac; done
+
+export USE_NVC
+export PEN_UPDATE
+export PEN_ENGINE
+
+PEN_ENGINE_ELISP="$PEN_ENGINE"
+
+if test "$PEN_ENGINE" = nil; then
+    PEN_ENGINE_ELISP=nil
+elif test -n "$PEN_ENGINE"; then
+    PEN_ENGINE_ELISP="\"$PEN_ENGINE\""
+else
+    PEN_ENGINE_ELISP=nil
+fi
+
+stdin_exists() {
+    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
+}
+
+# test -n "$person" || {
+#     echo "Person name required as parameter." 12
+#     exit 1
+# }
+
+if test "$#" -eq 0; then
+    person="$(pen-readln "Chatbot name")"
+else
+    person="$@"
+fi
+
+# PEN_USE_GUI is unset by design apparently
+
+if stdin_exists; then
+    context="$(cat)"
+fi
+
+if test -n "$context"
+    # Rather than specifying directly to the prompt function,
+    # this value is taken up and remembered for future prompting within the apostrophe
+    pen -nn -frametype "$FRAMETYPE" --pool -ic "(pen-engine $PEN_ENGINE_ELISP (progn (upd (guru $(cmd-nice-posix "$context")))(delete-other-windows)))"
+elif test -n "$person"; then
+    exec <&1
+    pen -nn -frametype "$FRAMETYPE" --pool -ic "(pen-engine $PEN_ENGINE_ELISP (progn (upd (apostrophe-start-chatbot-from-name $(cmd-nice-posix "$person") t))(delete-other-windows)))"
+else
+    pen -nn -frametype "$FRAMETYPE" --pool -ic "(pen-engine $PEN_ENGINE_ELISP (progn (upd (call-interactively 'apostrophe-start-chatbot-from-name))(delete-other-windows)))"
+fi
