1640302589

diff --git a/scripts/pen-tm b/scripts/pen-tm
--- a/scripts/pen-tm
+++ b/scripts/pen-tm
@@ -2180,7 +2180,7 @@ case "$f" in
 
     scrape|scrape-filter) {
         cap="$(pen-tm cap)"
-        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "f filter-with-fzf"
+        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-f filter-with-fzf"
     }
     ;;
 
@@ -2192,7 +2192,7 @@ case "$f" in
 
     scrape-things) {
         cap="$(pen-tm cap)"
-        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "f filter-things"
+        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-f filter-things"
     }
     ;;
 
@@ -2209,7 +2209,7 @@ case "$f" in
 
     scrapep) {
         cap="$(pen-tm capp)"
-        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "f filter-with-fzf"
+        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-f filter-with-fzf"
     }
     ;;
 
@@ -2500,7 +2500,7 @@ case "$f" in
             final_y="$(( y + 1 ))"
             pane_id="$(tmux neww -t "$CALLER_TARGET" -F "#{pane_id}" -P -n capture "stty stop undef; stty start undef; TTY= GOTO_COLUMN=$final_x GOTO_LINE=$final_y $EDITOR \"$np\"")"
 
-            if test $DO_SEND_KEYS = "f" && test "$EDITOR" = "pen-v"; then
+            if test $DO_SEND_KEYS = "pen-f" && test "$EDITOR" = "pen-v"; then
                 tmux send-keys -t "$pane_id" "C-k"
             else
                 :
@@ -3243,7 +3243,7 @@ case "$f" in
         pl "Use a command from the git hydra"
 
         pl "Remotes"
-        git remote -v | f urls
+        git remote -v | pen-f urls
 
         pen-pak
     }
@@ -3362,7 +3362,7 @@ case "$f" in
     ;;
 
     edit-file) {
-        paths="$(find . -maxdepth 1 -type f | sed 's/^..//')"
+        paths="$(find . -maxdepth 1 -type pen-f | sed 's/^..//')"
         if [ -n "$paths" ]; then
             paths="$(pl "$paths" | pen-str uniq | pen-tm -f -i spv -noerror "mfz -p" | umn)"
             pl "$paths" | awk1 | while IFS=$'\n' read -r line; do
@@ -3418,7 +3418,7 @@ case "$f" in
     ;;
 
     open-dirs) {
-        selections="$(pen-tm -s -fout spv -noerror "F find-no-git -d | mfz")"
+        selections="$(pen-tm -s -fout spv -noerror "pen-f find-no-git -d | mfz")"
         if [ -n "$selections" ]; then
             printf -- "%s\n" "$selections" | \
             while read -r line; do
@@ -3433,7 +3433,7 @@ case "$f" in
     ;;
 
     open-files) {
-        selections="$(pen-tm -s -fout spv -noerror "F f | mfz")"
+        selections="$(pen-tm -s -fout spv -noerror "pen-f f | mfz")"
         if [ -n "$selections" ]; then
             printf -- "%s\n" "$selections" | \
             while read -r line; do
@@ -3463,7 +3463,7 @@ case "$f" in
         IFS= read -rd '' input < <(cat /dev/stdin)
 
         export HAS_STDOUT
-        sout="$(set -o pipefail; printf -- "%s" "$input" | pen-tm spv -noerror "f filter-with-fzf" | cat)"
+        sout="$(set -o pipefail; printf -- "%s" "$input" | pen-tm spv -noerror "pen-f filter-with-fzf" | cat)"
         ret="$?"
 
         if test "$ret" -eq 0; then
