1641960124

diff --git a/scripts/pen-eipe b/scripts/pen-eipe
--- a/scripts/pen-eipe
+++ b/scripts/pen-eipe
@@ -1,6 +1,9 @@
 #!/bin/bash
 export TTY
 
+export PS4='+	"$(basename $0)"	${LINENO}	 '
+# set -xv
+
 tf_pipe_buffer="$(0</dev/null pen-tf pipe_buffer txt || echo /dev/null)"
 
 cat > "$tf_pipe_buffer"
@@ -23,6 +26,12 @@ pen -notm -nw --pool "$tf_pipe_buffer"
 
 exec 1>&3
 
-cat "$tf_pipe_buffer"
+# This hasn't failed on me yet
+if test -f "$tf_pipe_buffer"; then
+    cat "$tf_pipe_buffer"
+else
+    echo "File '$tf_pipe_buffer' does not exist" 1>&2
+    pen-pak
+fi
 
 trap "rm $(cmd "$tf_pipe_buffer") 2>/dev/null" 0
