11.09.22

diff --git a/scripts/pen-tm b/scripts/pen-tm
--- a/scripts/pen-tm
+++ b/scripts/pen-tm
@@ -2233,7 +2233,7 @@ case "$f" in
 
     scrape|scrape-filter) {
         cap="$(pen-tm cap)"
-        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-F filter-with-fzf"
+        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-f filter-with-fzf"
     }
     ;;
 
@@ -2245,7 +2245,7 @@ case "$f" in
 
     scrape-things) {
         cap="$(pen-tm cap)"
-        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-F filter-things"
+        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-f filter-things"
     }
     ;;
 
@@ -2262,7 +2262,7 @@ case "$f" in
 
     scrapep) {
         cap="$(pen-tm capp)"
-        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-F filter-with-fzf"
+        printf -- "%s" "$cap" | pen-tm -f -S -tout nw -noerror "pen-f filter-with-fzf"
     }
     ;;
 
@@ -3268,7 +3268,7 @@ case "$f" in
         pl "Use a command from the git hydra"
 
         pl "Remotes"
-        git remote -v | pen-F urls
+        git remote -v | pen-f urls
 
         pen-pak
     }
@@ -3387,7 +3387,7 @@ case "$f" in
     ;;
 
     edit-file) {
-        paths="$(find . -maxdepth 1 -type pen-F | sed 's/^..//')"
+        paths="$(find . -maxdepth 1 -type f | sed 's/^..//')"
         if [ -n "$paths" ]; then
             paths="$(pl "$paths" | pen-str uniq | pen-tm -f -i spv -noerror "mfz -p" | umn)"
             pl "$paths" | awk 1 | while IFS=$'\n' read -r line; do
@@ -3494,7 +3494,7 @@ case "$f" in
         IFS= read -rd '' input < <(cat /dev/stdin)
 
         export HAS_STDOUT
-        sout="$(set -o pipefail; printf -- "%s" "$input" | pen-tm spv -noerror "pen-F filter-with-fzf" | cat)"
+        sout="$(set -o pipefail; printf -- "%s" "$input" | pen-tm spv -noerror "pen-f filter-with-fzf" | cat)"
         ret="$?"
 
         if test "$ret" -eq 0; then
